### ISSUE TITLE
If no password is given, try to connect in offline mode

### ISSUE THREAD

**Issue by rom1504** [AlexKvazos/MinecraftChat#2]
Would be useful for servers in offline mode

**Comment by AlexKvazos** [comment]
Good idea, will do.

**Comment by Darker** [comment]
Please this would be really useful! :)

**Comment by rom1504** [comment]
That needs to be tried, but I think the only thing needed for this might be to remove the required there https://github.com/AlexKvazos/MinecraftChat/blob/master/public/templates/modals/connect.html#L21
