### ISSUE TITLE
[QUESTION] Are passwords sent to the server? 

### ISSUE THREAD

**Issue by Samistine** [AlexKvazos/MinecraftChat#5]
I want to know if passwords are sent to the server, if they are could you consider generating the session token on the client and then sending that instead.

**Comment by AlexKvazos** [comment]
They are sent to the server but over an HTTPS connection.

**Comment by Samistine** [comment]
Anyway you could generate the session token on the client then send it to
the server instead?

**Comment by AlexKvazos** [comment]
The server is what sends your credentials to the minecraft server so we need the credentials to reach the server. I don't see a problem with this, all websites do the same when logging you in, you send a POST request with your login data.

**Comment by Samistine** [comment]
Well the client can generate the client access token and session token and
forward that to the webserver and create bots using that instead. It makes
it safer and your less likely to be targeted for password collection.

**Comment by rom1504** [comment]
I think it might be a good idea to have an option to give the token instead of the password (you can pass that instead of the password in mineflayer createBot's options)

**Comment by AlexKvazos** [comment]
If the client sends an encrypted token, the data still has to be unencrypted on the server side to be sent to the username and password fields of the mineflayer bot.

**Comment by Samistine** [comment]
No no, Mojang allows you to use a session token to sign into servers, this
token is reset every time you log in, making it safer to send them the
users actual password.

**Comment by rom1504** [comment]
Yeah, and you can pass that token in accessToken (see https://github.com/andrewrk/mineflayer/blob/master/doc/api.md#mineflayercreatebotoptions that I just documented)

**Comment by AlexKvazos** [comment]
I see, but in order to get that accessToken don't I have to send the credentials to mineflayer? It still involves sending the credentials to a server.

**Comment by Samistine** [comment]
You can generate the token using Monjangs rest api from the client.

**Comment by AlexKvazos** [comment]
I can give it a go some day. If you are down, It be nice if you can send a PR :)

**Comment by Samistine** [comment]
I will try the best I can, but I have very very little experience with this programming language/api

**Comment by AlexKvazos** [comment]
Closed due to inactivity
